type User {
  id: ID!
  firstName: String
  lastName: String
  email: String!
  username: String!
  createdAt: String!
  updatedAt: String!
}

type Me {
  user: User!
  posts(after: ID): [Post]!
}

extend type Query {
  me: Me!
}
