version: '3'

services:
  database:
    image: 'postgres:14.1-alpine'
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - matefeed_database:/var/lib/postgresql/data
    restart: always

volumes:
  matefeed_database:
